### ISSUE TITLE
why in user.player.nameCard.banner is same and the navbar? 

### ISSUE THREAD

**Issue by kadistudio** [kravetsone/enkaNetwork#2]
![image](https://user-images.githubusercontent.com/70886239/200172526-8510ed7e-94a8-4f55-afd5-0ec4756b447f.png)

im trying to get this but instead,
![kamisato-ayato-ripple](https://user-images.githubusercontent.com/70886239/200172585-be77805b-6a97-4571-a465-1e996fb2199c.png)

i get this as an output.
![kamisato-ayato-ripple-01](https://user-images.githubusercontent.com/70886239/200172593-30328dd2-082b-4738-9d63-d31092ae581b.png)

**Comment by kadistudio** [comment]
i would like to incorporate the enkanetwork so no need for continuous updating when leveling up.

![image](https://user-images.githubusercontent.com/70886239/200172671-7af5e5f2-9193-4f0f-8aea-02903e1a7b8f.png)

**Comment by kravetsone** [comment]
# FIxed in [**`enkaNetwork@1.1.3`**](https://github.com/kravetsone/enkaNetwork/releases/tag/enkaNetwork%401.1.3)

Thank you for your message) I am very glad that you left it... 
Recently a new module appeared immediately ahead of mine
In this regard, I still have doubts about whether someone is using my module at all...
Appeared later but collected 15 thousand downloads against my 300. It is very demotivating.
Your message gave me more motivation) I'm waiting for feedback from you again.

**Comment by kadistudio** [comment]
i also want to know why there's no birthday indicated in your lib? or is this hidden? somewhere not accessible by the public?

**Comment by kravetsone** [comment]
Player birthday? The library supports everything that the api gives ([docs](https://api.enka.network/#/api)).
Api does not provide this, which means that there is no such thing in the library.

Most likely, yes, genshin does not allow you to get a player's birthday.

**Comment by kadistudio** [comment]
the issue still persists, the navbar and banner is the same output (the one you see when u check your friends)? how do i get this >>
![image](https://user-images.githubusercontent.com/70886239/200344271-cb24227b-80cc-4e8a-a414-15e564ce1aae.png)

**Comment by kadistudio** [comment]
also whenever the user have the normal namecard, will it show?

**Comment by kravetsone** [comment]
> проблема все еще сохраняется, панель навигации и баннер выводятся одинаково (тот, который вы видите, когда проверяете своих друзей)? как мне это получить >> ![изображение](https://user-images.githubusercontent.com/70886239/200344271-cb24227b-80cc-4e8a-a414-15e564ce1aae.png)

Sorry I forgot to apply the command `tsc ./`... In **`enkaNetwork@1.1.4`** this has definitely been fixed...  Once again, I'm sorry for this.

**Comment by kadistudio** [comment]
when will this 1.1.4 will be? im trying to incorporate your npm to my discord bot so bad. will this include the beginner namecard? because im getting an error because this might not be included?

![genshin-impact-a-new-world](https://user-images.githubusercontent.com/70886239/200351035-a18c1094-8296-42c8-90db-a181c466ef79.png)
![genshin-impact-a-new-world-01](https://user-images.githubusercontent.com/70886239/200351053-247316a5-bd85-4804-95fa-4da7b97db690.png)

**Comment by kadistudio** [comment]
also having this error when fetching the user "868503961"
![image](https://user-images.githubusercontent.com/70886239/200356517-b975a6c3-2521-42c8-a162-bde78228ed71.png)

**Comment by kravetsone** [comment]
> # when will this 1.1.4 will be? 
### At that time, the version had already been published.
![image](https://user-images.githubusercontent.com/57632712/200601248-338e7b0e-f1c6-4fc9-bc19-fcbdf3a1d6a6.png)

> # Will this include the beginner namecard?

### Navbar image for beginner namecard does not exist so you will get a **`undefined`** instead, but the banner you need is there 

![image](https://user-images.githubusercontent.com/57632712/200601982-66c96ff7-11b5-4b0c-91ff-358ed124d984.png)

> # ...because im getting an error because this might not be included?
### The error could have occurred due to the lack of navbar image, but at the moment ([enkaNetwork@1.1.5](https://github.com/kravetsone/enkaNetwork/releases/tag/enkaNetwork%401.1.5)) everything is fine.
